name: "Publish Documentation to NIST Pages"

on: [push, pull_request, delete]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: usnistgov/Docs4NIST@0.7
        with:
          docs-folder: docs/
          formats: |-
            epub
            pdf
          pip-requirements: 'docs-requirements.txt'
